config/routes.rb
Libreria::Application.routes.draw do

  resource :about, :only => :show , :controller => "about"
  resource :mapa, :only => :show, :controller => "mapa"

  resources :cuentas do
    resources :reservas
  end
  resources :reservas
  resources :ventas

  resources :cuentas do
    member do
      put "vaciar_carrito"
    end
    resources :compras do
      member do
        put "comprar"
      end
    end
  end

  get "log_in" => "sessions#new", :as => "log_in"
  get "log_out" => "sessions#destroy", :as => "log_out"

  get "sign_up" => "cuentas#new", :as => "sign_up"

  resources :sessions

  resources :contactos

  resources :libros

  resources :categorias

  resources :proximos_libros

  resources :agotados

  resources :pendientes

  root :to => 'libros#index'

end

app/models/compra.rb
class Compra < ActiveRecord::Base
  belongs_to :libro
  belongs_to :cuenta

  before_save :calcula_precio_total
  before_save :calcula_stock_final
  after_destroy :recalcular_stock

  validates_presence_of :fecha_compra, :libro_id, :cuenta_id, :cantidad #:pendiente_comprar

  validates :cantidad, :numericality => {:less_than_or_equal_to => Proc.new {|c| c.libro.stock}}, :on => :create
  #validates :cantidad, :with => :cantidad_correcta

  #def cantidad_correcta
    #if
      #errors.add(:cantidad, "no es correcta")
    #end
  #end
  #:private

  scope :comprado ,where(:comprado => true)
  scope :carrito ,where(:comprado => false)



  def calcula_precio_total
    self.precio_total = self.cantidad * self.libro.precio
  end
  private :calcula_precio_total

  def calcula_stock_final # al hacer una compra, resto el stock disponible menos la cantidad comprada
    libro.stock -= self.cantidad
    libro.save
  end
  private :calcula_stock_final

  def recalcular_stock #al eliminar el carrito, sumo la cantidad al stock disponible
    libro.stock +=self.cantidad
    libro.save
  end
  private :recalcular_stock



end

app/controllers/compras_controller.rb
class ComprasController < ApplicationController

   def index
    #@compras = Compra.comprado
    @cuenta = Cuenta.find(params[:cuenta_id])
    if params[:cuenta_id]
      @compras = Cuenta.find(params[:cuenta_id]).compras
    elsif current_cuenta.administrador?
      @compras = Compra.all
    else
      @compras = current_cuenta.compras
    end
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @compras }
    end
  end

  # GET /libros/1
  # GET /libros/1.json
  def show
    @compra = Compra.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @compra }
    end
  end

  # GET /libros/new
  # GET /libros/new.json
  def new
    @libros = Libro.find(params[:libro_id])
    @cuenta = Cuenta.find(params[:cuenta_id])
    @compra = @cuenta.compras.new(:libro => @libros, :fecha_compra => Date.today)

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @compra }
    end
  end

  def create
    @compra = Compra.new(params[:compra])
    #@compra.precio_total = @Compra.cantidad * @carrito.libro.precio
    if @compra.save
      redirect_to cuenta_compras_path(current_cuenta), notice: 'Libro anyadido a Compra sin problemas'
    else
      render action: "new"
    end
  end

  def edit
    @compra = Compra.find(params[:id])
  end

  def update
    @compra=Compra.find(params[:id])
    if @compra.update_attributes(params[:Compra])
      redirect_to edit_cuenta_path(current_cuenta)
    else
      render action: "edit"
    end
  end
  # DELETE /libros/1
  # DELETE /libros/1.json
  def destroy
    @compra = Compra.find(params[:id])
    cuenta = @compra.cuenta
    @compra.destroy

    respond_to do |format|
      format.html { redirect_to cuenta_compras_path(current_cuenta) }
      format.json { head :ok }
    end
  end
end

app/views/compras/edit.html.haml
%h2#compra Formulário Modificar compra
= semantic_form_for [@cuenta, @compra], :url => cuenta_compras_path(@cuenta), :html => { :multipart => true} do |f|
  -if @compra.errors.any?
    #error_explanation
      %h2= "#{pluralize(@compra.errors.count, "error")} prohibited this libro from being saved:"
      %ul
        - @compra.errors.full_messages.each do |msg|
          %li= msg

  = f.inputs :name => " Añadir a compra" do
    %li.string.input.stringish
      %label.label Título:
      %p#compra= @compra.libro.titulo
    -#= f.input :libro_id
    -#= f.input :cuenta_id
    = f.input :cantidad
    %li.string.input.stringish
      %label.label Precio Libro:
      %p.precio_libro= @compra.libro.precio
    %li.string.input.stringish
      %label.label Precio Total:
      %p.precio_total= @compra.libro.precio
    = f.input :fecha_compra, :as=> :string
    = f.input :libro_id, :as => :hidden
    = f.input :cuenta_id, :as => :hidden
  = f.buttons

app/views/compras/index.html.haml
- unless @compras.empty?
  -#= form_tag finalizar_compra_cuenta_compras_path(@cuenta) do
  %table.span-18
    %tr
      %th Mi Compra
      %th Cantidad
      %th Precio
      %th Editar
      %th Eliminar
      %th Comprar
    - @cuenta.compras.each do |compra|
      %tr
        %td= link_to compra.libro.titulo, compra.libro
        %td.centrado= compra.cantidad
        %td.centrado= sprintf("€%0.02f",compra.precio_total)
        -#%td= compra.precio_total_compras
        %td= link_to image_tag("edit.png"), edit_cuenta_compra_path(current_cuenta,compra)
        %td= link_to image_tag("destroy.jpg"), cuenta_compra_path(current_cuenta,compra), :confirm => "Desea eliminar el libro #{compra.libro.titulo} del carrito?", :method => :delete
        -#%td= check_box "pendiente_comprar[#{compra.id}]", :collection => [["No",0],["Si",1]]
        %td= link_to 'Comprar', edit_cuenta_compra_path(current_cuenta,compra), :class => "comprar_libro"

    %tr.clear
      %th.total{:colspan => 2} Total:
      %th.precio_total_compras= sprintf("€%0.02f",@cuenta.precio_total_compras)
      %th{:colspan => 3}
  -#.enlaceboton
    -#= link_to 'Finalizar Compra', edit_cuenta_path(current_cuenta), :notice => "Los libros han sido comprados sin problemas"

    -#= submit_tag "Finalizar compra"
  - if current_cuenta
    =button_to 'Vaciar Carrito', vaciar_carrito_cuenta_path(@cuenta), :confirm => "Desea vaciar su carrito entero?", :method => :put

app/views/compras/new.html.haml
%h2#compra Formulário Comprar Libro
= semantic_form_for [@cuenta, @compra], :url => cuenta_compras_path(@cuenta), :html => { :multipart => true} do |f|
  -if @compra.errors.any?
    #error_explanation
      %h2= "#{pluralize(@compra.errors.count, "error")} prohibited this libro from being saved:"
      %ul
        - @compra.errors.full_messages.each do |msg|
          %li= msg

  = f.inputs :name => " Añadir a compra" do
    %li.string.input.stringish
      %label.label Título:
      %p#compra= @compra.libro.titulo
    -#= f.input :libro_id
    -#= f.input :cuenta_id
    = f.input :cantidad
    %li.string.input.stringish
      %label.label Stock:
      %p.stock=@compra.libro.stock
    %li.string.input.stringish
      %label.label Stock Final:
      %p.stock_final= @compra.libro.stock
    %li.string.input.stringish
      %label.label Precio Libro:
      %p.precio_libro= @compra.libro.precio
    %li.string.input.stringish
      %label.label Precio Total:
      %p.precio_total= @compra.libro.precio
    = f.input :fecha_compra, :as=> :string
    = f.input :libro_id, :as => :hidden
    = f.input :cuenta_id, :as => :hidden
  = f.buttons do
    = f.commit_button "Añadir a Carrito"