config/routes.rb
Libreria::Application.routes.draw do

  resource :about, :only => :show , :controller => "about"
  resource :mapa, :only => :show, :controller => "mapa"

  resources :cuentas do
    resources :reservas
  end
  resources :reservas
  resources :ventas

  resources :cuentas do
    member do
      put "vaciar_carrito"
    end
    resources :compras do
      member do
        put "comprar"
      end
    end
  end

  get "log_in" => "sessions#new", :as => "log_in"
  get "log_out" => "sessions#destroy", :as => "log_out"

  get "sign_up" => "cuentas#new", :as => "sign_up"

  resources :sessions

  resources :contactos

  resources :libros

  resources :categorias

  resources :proximos_libros

  resources :agotados

  resources :pendientes

  root :to => 'libros#index'

end

app/models/libro.rb
class Libro < ActiveRecord::Base
  attr_accessible :titulo,:autor,:editorial,:anyo,:paginas,:precio,:descripcion,:photo,:proximolibro,:stock,:categoria_id, :categoria_nombre, :fecha_disponible, :state
  belongs_to :categoria
  has_many :reservas
  has_many :compras

  validates_presence_of :precio,:titulo,:categoria_nombre,:state

  after_save :actualiza_state



  define_index do #inserto los campos que quiero buscar
    indexes titulo #los campos de la tabla libros, que es con la que estoy trabajando
    indexes autor # es el nombre del campo de la tabla Libro
    indexes descripcion
    indexes editorial
    indexes categoria(:categoria_nombre), :as => :categoria # quiero buscar por categorias, pero categoria no es un campo de Libro, por lo que utilizo la tabla categoria y el campo categoria_nombre

  end


  #def nombre_categoria=(v)

  ## buscar en Categoria por el nombre y si no existe crearla
  #categoria_encontrada =  Categoria.find_by_nombre(v)
  #self.categoria = categoria_encontrada
  #end



  #paperclip
  has_attached_file :photo, :styles => { :thumb => "50x50", :small => "50x50"}
  validates_attachment_size :photo, :less_than => 2.megabytes
  validates_attachment_content_type :photo, :content_type => ['image/jpeg','image/png','image/jpg']

  scope :proximos, where(:state => :proximo)
  scope :disponibles, where(:state => :disponible)
  scope :agotados, where(:state => :agotado )

  state_machine :state do

    event :esperar do #cuando el stock llega a 0
      transition :proximo => :agotado
    end

    event :recibir do
      transition :proximo => :disponible
    end

    event :agotar do
      transition :disponible => :agotado
    end

    event :encargar do
      transition :agotado => :disponible
    end

    event :cancelar do
      transition :agotado => :proximo
    end
  end

  #def self.lista_categoria
  #all.map(&:categoria).uniq
  #end

  def categoria_nombre
    categoria.try(:categoria_nombre)
  end
  def categoria_nombre=(nombre)
    self.categoria=Categoria.find_or_create_by_categoria_nombre(nombre) if nombre.present?
  end

  def actualiza_state
    if stock == 0
      self.agotar
    end

  end


end

app/controllers/libros_controller.rb
class LibrosController < ApplicationController
  # GET /libros
  # GET /libros.json
  def index
    @libros = Libro.disponibles.paginate(:page => params[:page], :per_page => 4)
    #@libros = Libro.search(params[:search])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @libros }
    end
  end

  # GET /libros/1
  # GET /libros/1.json
  def show
    @libro = Libro.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @libro }
    end
  end

  # GET /libros/new
  # GET /libros/new.json
  def new
    @libro = Libro.new #(:anyo => 2011)

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @libro }
    end
  end

  # GET /libros/1/edit
  def edit
    @libro = Libro.find(params[:id])
  end

  # POST /libros
  # POST /libros.json
  def create
    @libro = Libro.new(params[:libro])

    if @libro.save
      redirect_to @libro, notice: 'Libro was successfully created.'
    else
      render action: "new"
    end
  end

  # PUT /libros/1
  # PUT /libros/1.json
  def update
    @libro = Libro.find(params[:id])

    respond_to do |format|
      if @libro.update_attributes(params[:libro])
        format.html { redirect_to @libro, notice: 'Libro was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @libro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /libros/1
  # DELETE /libros/1.json
  def destroy
    @libro = Libro.find(params[:id])
    @libro.destroy

    respond_to do |format|
      format.html { redirect_to libros_url }
      format.json { head :ok }
    end
  end
end

app/helpers/libros_helper.rb
module LibrosHelper
end

app/views/libros/_form.html.haml
= semantic_form_for @libro, :html => { :multipart => true, :autocomplete=> :off} do |f|

  = f.inputs :name => "Añadir libro" do
    = f.input :titulo
    = f.input :autor
    = f.input :editorial
    = f.input :categoria_nombre, :label => "Categoria", data: {autocomplete_source: categorias_path}
    = f.input :anyo, :label => "Año"
    = f.input :paginas, :label => "Páginas"
    = f.input :precio
    = f.input :descripcion, :as => :text, :label => "Descripción"
    = f.input :stock
    = f.input :photo, :as=> :file
    = f.input :fecha_disponible, :label => "Disponible desde", :as => :string, :input_html => {:class => "fecha"}
    = f.input :state, :as=> :select, :collection => [["Disponible","disponible"],["Proximo","proximo"],["Agotado","agotado"]], :label => "Ya a la Venta?"
  = f.buttons do
    = f.commit_button "Crear Libro"

  -#.field
    -#= f.label :titulo
    -#= f.text_field :titulo
  -#.field
    -#= f.label :autor
    -#= f.text_field :autor
  -#.field
    -#= f.label :editorial
    -#= f.text_field :editorial
  -#.field
    -#= f.label :categoria
    -#= f.text_field :categoria
  -#.field
    -#= f.label :anyo
    -#= f.text_field :anyo
  -#.field
    -#= f.label :paginas
    -#= f.number_field :paginas
  -#.field
    -#= f.label :precio
    -#= f.text_field :precio
  -#.field
    -#= f.label :descripcion
    -#= f.text_field :descripcion
  -#.actions
    -#= f.submit 'Save'

app/views/libros/edit.html.haml
-if current_cuenta && current_cuenta.administrador?
  %h1 Editing libro

  = render 'form'

  = link_to 'Back', libros_path

app/views/libros/index.html.haml
= form_tag libros_path, {:method => :get, :id => "search"} do
  = text_field_tag :search, params[:search]
  = submit_tag "Search", :name => "nil"

.titulolibros
  %h1 Libros Disponibles

%table.span-18.clear
  %tr
    <th> Título</th>
    %th Stock
    %th Comprar
    -#%th Autor
    -#%th Editorial
    -#%th Categoria
    -#%th Año
    -#%th Paginas
    -#%th Precio
    -#%th Descripcion
    -#%th
    -#%th
    -#%th
  - @libros.each do |libro|
    %tr
      %td= link_to libro.titulo,libro
      %td= libro.stock
      - if current_cuenta
        %td= link_to image_tag(libro.photo.url(:thumb)), new_cuenta_compra_path(current_cuenta, :libro_id => libro)
      - if !current_cuenta
        %td= link_to image_tag(libro.photo.url(:thumb)),libro
      -#%td= libro.autor
      -#%td= libro.editorial
      -#%td= libro.categoria -#%td= libro.anyo
      -#%td= libro.paginas
      -#%td= libro.precio
      -#%td= libro.descripcion
      -#%td= link_to 'Show', libro
      -#%td= link_to 'Edit', edit_libro_path(libro)
      - if current_cuenta && current_cuenta.administrador?
        %td= link_to image_tag("destroy.jpg"), libro, :confirm => 'Are you sure?', :method => :delete
  - if current_cuenta && current_cuenta.administrador?
    .enlaceboton.izquierda
      = link_to 'Añadir Libro', new_libro_path
= will_paginate

app/views/libros/new.html.haml
= render 'form'

= link_to 'Back', libros_path

app/views/libros/show.html.haml
%p#notice= notice

%p
  %b Título:
  =@libro.titulo
%p
  %b Autor:
  = @libro.autor
%p
  %b Editorial:
  = @libro.editorial
%p
  %b Categoria:
  = @libro.categoria_nombre
  -#= @libro.categoria.categoria_nombre if @libro.categoria
%p
  %b Año Publicación:
  = @libro.anyo
%p
  %b Páginas:
  = @libro.paginas
%p
  %b Precio:
  = sprintf("€%0.02f",@libro.precio)
%p
  %b Stock:
  = @libro.stock
%p
  %b Fecha Disponible:
  = l(@libro.fecha_disponible, :format=>"%d/%m/%Y")

%dl
  %dt Sinopsis:
  %dd= @libro.descripcion

-#%p
  -#%b Photo
  -#= @libro.photo
-#%p
  -#%b Disponible?
  -#= libro.proximolibro
= link_to 'Atras', libros_path
- if current_cuenta && current_cuenta.administrador?
  = link_to 'Edit', edit_libro_path(@libro)