config/routes.rb
Libreria::Application.routes.draw do

  resource :about, :only => :show , :controller => "about"
  resource :mapa, :only => :show, :controller => "mapa"

  resources :cuentas do
    resources :reservas
  end
  resources :reservas
  resources :ventas

  resources :cuentas do
    member do
      put "vaciar_carrito"
    end
    resources :compras do
      member do
        put "comprar"
      end
    end
  end

  get "log_in" => "sessions#new", :as => "log_in"
  get "log_out" => "sessions#destroy", :as => "log_out"

  get "sign_up" => "cuentas#new", :as => "sign_up"

  resources :sessions

  resources :contactos

  resources :libros

  resources :categorias

  resources :proximos_libros

  resources :agotados

  resources :pendientes

  root :to => 'libros#index'

end

app/models/cuenta.rb
class Cuenta < ActiveRecord::Base
  attr_accessible :email, :password, :password_confirmation, :administrador, :nombre, :apellido, :nif, :direccion, :ciudad, :codigo, :telefono, :provincia
  has_many :reservas, :dependent => :destroy
  has_many :compras, :dependent=> :restrict

  before_destroy :puedo_borrar?

  def puedo_borrar?
    if administrador == true
      false
    end
  end

  attr_accessor :password
  before_save :encrypt_password
  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, :on => :create


 def self.authenticate(email, password)
    cuenta = find_by_email(email)
    if cuenta && cuenta.password_hash == BCrypt::Engine.hash_secret(password, cuenta.password_salt)
      cuenta
    else
      nil
    end
  end
  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end

  #validates :nombre, :presence => true, :on => :update
  #validates :apellido, :presence => true, :on => :update
  #validates :nif, :presence => true, :on => :update
  #validates :direccion, :presence =>true, :on => :update
  #validates :ciudad, :presence => true, :on => :update
  #validates :codigo, :presence => true, :on => :update
  #validates :telefono, :presence => true, :on => :update
  #validates :provincia, :presence => true, :on => :update
  def precio_total_compras
    compras.sum(:precio_total)
    #p = 0
    #compras.each do |compra|
      #p += (compra.precio_total || 0)
    #end
    #return p
  end
end

app/controllers/cuentas_controller.rb
class CuentasController < ApplicationController
before_filter :correct_cuenta, :only => [:edit,:update]

  # GET /cuenta
  # GET /cuenta.json
  def vaciar_carrito
    current_cuenta.compras.clear
    redirect_to cuenta_compras_path(current_cuenta)
  end


  def index
    @cuentas = Cuenta.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @cuentas }
    end
  end

  # GET /cuenta/1
  # GET /cuenta/1.json
  def show
    @cuenta = Cuenta.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @cuenta }
    end
  end

  # GET /cuenta/new
  # GET /cuenta/new.json
  def new
    @cuenta = Cuenta.new
  end
  # GET /cuenta/1/edit
  def edit
    @cuenta = Cuenta.find(params[:id])
    @compras = @cuenta.compras.comprado
  end

  # POST /cuenta
  # POST /cuenta.json
  def create
    @cuenta = Cuenta.new(params[:cuenta])
    if @cuenta.save
      redirect_to log_in_url, notice: 'Signed up!'
    else
      render action: "new"
    end
  end

  # PUT /cuenta/1
  # PUT /cuenta/1.json
  def update
    @cuenta = Cuenta.find(params[:id])

    respond_to do |format|
      if @cuenta.update_attributes(params[:cuenta])
        format.html { redirect_to @cuenta, notice: 'La cuenta ha sido actualizada' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @cuenta.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cuenta/1
  # DELETE /cuenta/1.json
  def destroy
    @cuenta = Cuenta.find(params[:id])
    @cuenta.destroy

    respond_to do |format|
      format.html { redirect_to cuentas_url }
      format.json { head :ok }
    end
  end
end

 private
  def authenticate
      deny_access unless signed_in?
    end

  def correct_cuenta
    @cuenta = Cuenta.find(params[:id])

    redirect_to(root_path, :notice => "No tienes permiso para modificar esta cuenta.") unless current_cuenta == @cuenta
  end

app/helpers/cuenta_helper.rb
module CuentaHelper
end

app/views/cuentas/_compras.html.haml
- unless @cuenta.compras.empty?
  %table
    %tr
      %th Libros Comprados
      %th.centrado Cantidad
      %th.centrado Precio
    - @cuenta.compras.each do |compra|
      %tr
        %td= link_to compra.libro.titulo, compra.libro
        %td.centrado= compra.cantidad
        %td.centrado= sprintf("€%0.02f", compra.precio_total)
        -#%td= link_to image_tag("destroy.jpg"),cuenta_compra_path(current_cuenta,compra), :confirm => "Desea eliminar la reserva #{compra.libro.titulo}?", :method => :delete
    %tr
    %th.total{:colspan => 2} Total:
    %th.precio_total_compras= sprintf("€%0.02f",@cuenta.precio_total_compras)
    %th{:colspan => 3}

app/views/cuentas/_reservas.html.haml
- unless @cuenta.reservas.empty?
  %table
    %tr
      %th Libros Reservados
      %th Cantidad
      %th Editar
      %th Eliminar
    - @cuenta.reservas.each do |reserva|
      %tr
        %td= link_to reserva.libro.titulo, reserva.libro
        %td= reserva.cantidad
        %td= link_to image_tag("edit.png"), edit_cuenta_reserva_path(current_cuenta, reserva)
        %td= link_to image_tag("destroy.jpg"),cuenta_reserva_path(current_cuenta,reserva), :confirm => "Desea eliminar la reserva #{reserva.libro.titulo}?", :method => :delete

app/views/cuentas/edit.html.haml
= form_for @cuenta do |f|
  -if @cuenta.errors.any?
    #error_explanation
      %h2= "#{pluralize(@cuenta.errors.count, "error")} prohibited this cuenta from being saved:"
      %ul
        - @cuenta.errors.full_messages.each do |msg|
          %li= msg
  %fieldset.datos_personales
    %legend Datos Personales
    .field
      = f.label :nombre, :class => "label"
      = f.text_field :nombre, :size => "20"
    .field
      = f.label :apellido, :class => "label"
      = f.text_field :apellido, :size => "20"
    .field
      = f.label :nif, :class => "label"
      = f.text_field :nif, :size => "20"
    .field
      = f.label :direccion, :class => "label"
      = f.text_field :direccion, :size => "20"
    .field
      = f.label :ciudad, :class => "label"
      = f.text_field :ciudad, :size => "20"
    .field
      = f.label :codigo, :class => "label"
      = f.number_field :codigo, :size => "20"
    .field
      = f.label :telefono, :class => "label"
      = f.number_field :telefono, :size => "20"
    .field
      = f.label :provincia, :class => "label"
      = f.select( :provincia,['Castellon','Valencia','Alicante','Otras'], :include_blank =>true)
      -#= f.select :provincia, %w{Castellón Valencia Alicante}
  %fieldset.datos_cuenta
    %legend Datos Acceso
    .field
      = f.label :email, :class => "label"
      = f.text_field :email, :size => "20"
    .field
      = f.label :password, :class => "label"
      = f.password_field :password, :size => "20"
    .field
      = f.label :password_confirmation, :class => "label"
      = f.password_field :password_confirmation, :size => "20"
    - if current_cuenta && current_cuenta.administrador?
      .field
        =f.label :administrador
        =f.select( :administrador ,[['No', 0 ],['Si', 1]])

  .actions
    = f.submit 'Save'
    = link_to 'Back', cuentas_path

  = render :partial => 'reservas'
  = render :partial => 'compras'

app/views/cuentas/index.html.haml
%h1 Información de Cuenta

%table.span-6.clear
  %tr
    %th Email
    %th
    %th
    %th

  - @cuentas.each do |cuenta|
    %tr
      %td= mail_to cuenta.email
      %td= link_to image_tag("show.png"), cuenta
      %td= link_to image_tag("edit.png"), edit_cuenta_path(cuenta)
      %td=link_to image_tag("destroy.jpg"),cuenta, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Cuenta', new_cuenta_path

app/views/cuentas/new.html.haml
%h1 Sign Up
= form_for @cuenta do |f|
  %fieldset.datos_cuenta
    %legend Datos Acceso
    .field
      = f.label :email, :class => "label"
      = f.text_field :email, :size => "20"
    .field
      = f.label :password, :class => "label"
      = f.password_field :password, :size => "20"
    .field
      = f.label :password_confirmation, :class => "label"
      = f.password_field :password_confirmation, :size => "20"
    - if current_cuenta && current_cuenta.administrador?
      .field
        =f.label :administrador
        =f.select( :administrador ,[['No', 0 ],['Si', 1]])


  .actions
    = f.submit 'Registrarse'

app/views/cuentas/show.html.haml
%p#notice= notice

%p
  %b Email:
  = @cuenta.email
%p
  %b Nombre:
  = @cuenta.nombre
%p
  %b Apellido:
  = @cuenta.apellido
%p
  %b Nif:
  = @cuenta.nif
%p
  %b Direccion:
  = @cuenta.direccion
%p
  %b Ciudad:
  = @cuenta.ciudad
%p
  %b Codigo:
  = @cuenta.codigo
%p
  %b Provincia:
  = @cuenta.provincia
%p
  %b Telefono:
  = @cuenta.telefono
%p
  %b Administrador:
  = @cuenta.administrador


= render :partial => 'reservas'
= render :partial => 'compras'


-#= link_to 'Edit', edit_cuenta_path(@cuenta)
-#\|
= link_to 'Back', root_path