config/routes.rb
Libreria::Application.routes.draw do

  resource :about, :only => :show , :controller => "about"
  resource :mapa, :only => :show, :controller => "mapa"

  resources :cuentas do
    resources :reservas
  end
  resources :reservas
  resources :ventas

  resources :cuentas do
    member do
      put "vaciar_carrito"
    end
    resources :compras do
      member do
        put "comprar"
      end
    end
  end

  get "log_in" => "sessions#new", :as => "log_in"
  get "log_out" => "sessions#destroy", :as => "log_out"

  get "sign_up" => "cuentas#new", :as => "sign_up"

  resources :sessions

  resources :contactos

  resources :libros

  resources :categorias

  resources :proximos_libros

  resources :agotados

  resources :pendientes

  root :to => 'libros#index'

end

app/views/layouts/_menu.html.haml
%ul#menuinicio
  %li= link_to "Libros Disponibles", libros_path
  %li= link_to "Proximos Libros",proximos_libros_path
  %li= link_to "Libros Agotados", agotados_path
  -#- if current_cuenta && current_cuenta.administrador?
    -#%li= link_to "Libros Pendientes", pendientes_path
  - unless current_cuenta
    %li= link_to "Contacto", new_contacto_path

.clear

app/views/layouts/_menudesplegable.html.haml
- if signed_in?
  %ul#menu_desplegable
    %li
      Menu
      %ul
        %li#submenu= link_to "Cuenta", edit_cuenta_path(current_cuenta)
        - if current_cuenta && current_cuenta.administrador?
          %li#submenu= link_to "Peticiones", contactos_path
          %li#submenu= link_to "Usuarios", cuentas_path
        - if current_cuenta && !current_cuenta.administrador?
          %li#submenu= link_to "Contacto", new_contacto_path

app/views/layouts/_menuvertical.html.haml
%ul#menuvertical.span-6.clear
  %li= link_to "Sobre la Librería", about_path
  %li= link_to "Pedir Libro", new_contacto_path
  %li= link_to "Librería mas cercana", mapa_path
  %li= link_to "Categorias", categorias_path

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
<%= stylesheet_link_tag 'application', :media => 'screen' %>
<%= stylesheet_link_tag 'application' %>
  <!--[if IE 6]><%= stylesheet_link_tag 'ie6' %><![endif]-->
  <!--[if IE 7]><%= stylesheet_link_tag 'ie7' %><![endif]-->

app/views/layouts/application.html.haml
!!!
%html
%head
  %meta{charset: "UTF-8"}
  %title Libreria Fadrell
  = render 'layouts/stylesheets'
  = javascript_include_tag "application"
  = csrf_meta_tag

%body

  %header#cabezera
    - if !current_cuenta
      = link_to image_tag("paypal1.jpeg", :id => "imgpaypal"), "http://www.paypal.com"
    - if current_cuenta
      = link_to image_tag("carrito1.gif", :id => "imgcarrito"), cuenta_compras_path(current_cuenta)
      = link_to image_tag("paypal1.jpeg", :id => "imgpaypal"), "http://www.paypal.com"
    %h1#cabezerafadrell Librería Fadrell
    %p.centrado
      - if current_cuenta
        = "Logged in as #{current_cuenta.email}"
        = link_to "Salir", log_out_path
      - else
        = link_to "Registrarse", sign_up_path
        ||
        = link_to "Logearse", log_in_path
    = render 'layouts/menu'
    = render 'layouts/menudesplegable'
  .clear


  .container
    = render 'layouts/menuvertical'
    = yield